### ISSUE TITLE
Docker image doesn't appear to function

### ISSUE THREAD

**Issue by aegerton** [datascienceworkshops/dockerfiles#2]
Upon installing the image using the command as follows

$ docker run --rm -itv`pwd`:/data datascienceworkshops/data-science-at-the-command-line

The image appears to load correctly, but then doesn't operate.  There is no file directory as specified in the text.

Maybe I am doing something stupidly wrong!

**Comment by Crevax** [comment]
What OS and version of Docker are you using? Have you verified the directory your running the command from has file within in? If all went well, your terminal should look you've ssh'd into a different machine; so running commands like `whoami` or `pwd` will output those commands as executed within the container instead of your host machine.

Let me know if that's unclear.

**Comment by aegerton** [comment]
I am using Ubuntu Linux 17.10 and Docker CE Stable for Ubuntu (17.11, I think). Having used the pwd command, I am in the data directory, but it seems to be picking up the file system of the host machine rather than the container. Any idea why, please?

**Comment by Crevax** [comment]
The `/data` directory of the Docker image is empty by default, but you're able to mount files from the host machine into the container. That's what is happening with the `v` flag. The `'pwd'` portion that follows is actually an evaluation of the command on your host before utilizing it as a parameter. So whatever directory you run that command in is shared-mounted into the container. Changes you make in the directory on the host will appear in the container and vise versa. Does that clear things up?

**Comment by aegerton** [comment]
Yes, I think so.  However, I still can't locate the /home/vagrant and /book directories in the container. I am clearly doing something wrong, but can't figure out what.

**Comment by Crevax** [comment]
Apologies, I'm just getting started with the book; I've just had Vagrant and Docker experience throughout my career. Are you referring to section [2.3.2](https://www.datascienceatthecommandline.com/chapter-2-getting-started.html#executing-a-command-line-tool)? If so, I don't believe you're doing anything wrong. That section doesn't appear to have been fully updated to reference Docker instead of Vagrant.

`/home/vagrant` is automatically created when using Vagrant, and wouldn't exist in a Docker image or container unless explicitly added. Taking a look at the [Dockerfile](https://hub.docker.com/r/datascienceworkshops/data-science-at-the-command-line/~/dockerfile/) shows that `home/vagrant` doesn't exists. I also see the Docker image only pulls in the [tools](https://github.com/jeroenjanssens/data-science-at-the-command-line/tree/master/tools) directory, so those other references won't exist. Hopefully Jeroen will have an update for that soon.

In the meantime, I've taken a moment to create a [gitter room](https://gitter.im/data-science-at-the-command-line/Lobby) for people to discuss the book. I've also forked the project to see if I can help contribute updates to the resources. I'm excited to go through the book, so I'd like to help out where I can.

**Comment by jeroenjanssens** [comment]
Thanks again for fixing this @Crevax !

**Comment by aranmariaines** [comment]
Thanks @Crevax ! The book in the link (https://www.datascienceatthecommandline.com/chapter-2-getting-started.html) still shows the output example with ' home/vagrant' and I it was confusing.
